using DebtusTestTask.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public class CurrencyConfiguration : IEntityTypeConfiguration<Currency>
{
    public void Configure(EntityTypeBuilder<Currency> builder)
    {
        var currencyList = new Currency[]
        {
            new() { Id = "KYD", Name = "Cayman Islands Dollar" },
            new() { Id = "AFN", Name = "Afghanistan Afghani" },
            new() { Id = "ALL", Name = "Albanian Lek" },
            new() { Id = "DZD", Name = "Algerian Dinar" },
            new() { Id = "AOA", Name = "Angolan New Kwanza" },
            new() { Id = "ARS", Name = "Argentine Peso" }, // Объединено с "Argentina Pesos"
            new() { Id = "AWG", Name = "Aruban Florin" },
            new() { Id = "AUD", Name = "Australian Dollar" },
            new() { Id = "BSD", Name = "Bahamian Dollar" },
            new() { Id = "BHD", Name = "Bahraini Dinar" },
            new() { Id = "BDT", Name = "Bangladeshi Taka" },
            new() { Id = "BBD", Name = "Barbados Dollar" },
            new() { Id = "BZD", Name = "Belize Dollar" },
            new() { Id = "BMD", Name = "Bermudian Dollar" },
            new() { Id = "BTN", Name = "Bhutan Ngultrum" },
            new() { Id = "BOB", Name = "Bolivian Boliviano" },
            new() { Id = "BWP", Name = "Botswana Pula" },
            new() { Id = "BRL", Name = "Brazilian Real" },
            new() { Id = "BND", Name = "Brunei Dollar" },
            new() { Id = "BGN", Name = "Bulgarian Lev" },
            new() { Id = "BIF", Name = "Burundi Franc" },
            new() { Id = "CAD", Name = "Canadian Dollar" },
            new() { Id = "CVE", Name = "Cape Verde Escudo" },
            new() { Id = "XOF", Name = "CFA Franc BCEAO" },
            new() { Id = "XAF", Name = "CFA Franc BEAC" },
            new() { Id = "XPF", Name = "CFP Franc" },
            new() { Id = "CLP", Name = "Chilean Peso" },
            new() { Id = "CNY", Name = "Chinese Yuan Renminbi" },
            new() { Id = "COP", Name = "Colombian Peso" },
            new() { Id = "KMF", Name = "Comoros Franc" },
            new() { Id = "CRC", Name = "Costa Rican Colon" },
            new() { Id = "HRK", Name = "Croatian Kuna" },
            new() { Id = "CUP", Name = "Cuban Peso" },
            new() { Id = "CYP", Name = "Cyprus Pound" },
            new() { Id = "CZK", Name = "Czech Koruna" },
            new() { Id = "DKK", Name = "Danish Krona" },
            new() { Id = "DJF", Name = "Djibouti Franc" },
            new() { Id = "DOP", Name = "Dominican Peso" },
            new() { Id = "XCD", Name = "Eastern Caribbean Dollars" },
            new() { Id = "ECS", Name = "Ecuador Sucre" },
            new() { Id = "EGP", Name = "Egyptian Pound" },
            new() { Id = "SVC", Name = "El Salvador Colon" },
            new() { Id = "EEK", Name = "Estonian Krona" },
            new() { Id = "ETB", Name = "Ethiopian Birr" },
            new() { Id = "EUR", Name = "Euro" },
            new() { Id = "FKP", Name = "Falkland Islands Pound" },
            new() { Id = "FJD", Name = "Fiji Dollar" },
            new() { Id = "GMD", Name = "Gambian Dalasi" },
            new() { Id = "GHS", Name = "Ghanaian Cedi" },
            new() { Id = "GIP", Name = "Gibraltar Pound" },
            new() { Id = "XAU", Name = "Gold (oz.)" },
            new() { Id = "GTQ", Name = "Guatemalan Quetzal" },
            new() { Id = "GNF", Name = "Guinea Franc" },
            new() { Id = "GYD", Name = "Guyanan Dollar" },
            new() { Id = "HTG", Name = "Haitian Gourde" },
            new() { Id = "HNL", Name = "Honduran Lempira" },
            new() { Id = "HKD", Name = "Hong Kong Dollar" },
            new() { Id = "HUF", Name = "Hungarian Forint" },
            new() { Id = "ISK", Name = "Iceland Krona" },
            new() { Id = "XDR", Name = "IMF Special Drawing Right" },
            new() { Id = "INR", Name = "Indian Rupee" },
            new() { Id = "IDR", Name = "Indonesian Rupiah" },
            new() { Id = "IRR", Name = "Iranian Rial" },
            new() { Id = "IQD", Name = "Iraqi Dinar" },
            new() { Id = "ILS", Name = "Israeli New Shekel" },
            new() { Id = "JMD", Name = "Jamaican Dollar" },
            new() { Id = "JPY", Name = "Japanese Yen" },
            new() { Id = "JOD", Name = "Jordanian Dinar" },
            new() { Id = "KHR", Name = "Kampuchean Riel" },
            new() { Id = "KZT", Name = "Kazakhstan Tenge" },
            new() { Id = "KES", Name = "Kenyan Shilling" },
            new() { Id = "KRW", Name = "Korean Won" },
            new() { Id = "KWD", Name = "Kuwaiti Dinar" },
            new() { Id = "LAK", Name = "Lao Kip" },
            new() { Id = "LVL", Name = "Latvian Lats" },
            new() { Id = "LBP", Name = "Lebanese Pound" },
            new() { Id = "LSL", Name = "Lesotho Loti" },
            new() { Id = "LRD", Name = "Liberian Dollar" },
            new() { Id = "LYD", Name = "Libyan Dinar" },
            new() { Id = "LTL", Name = "Lithuanian Litas" },
            new() { Id = "MOP", Name = "Macau Pataca" },
            new() { Id = "MGA", Name = "Malagasy Franc" },
            new() { Id = "MWK", Name = "Malawi Kwacha" },
            new() { Id = "MYR", Name = "Malaysian Ringgit" },
            new() { Id = "MVR", Name = "Maldive Rufiyaa" },
            new() { Id = "MTL", Name = "Maltese Lira" },
            new() { Id = "MRU", Name = "Mauritanian Ouguiya" },
            new() { Id = "MUR", Name = "Mauritius Rupee" },
            new() { Id = "MXN", Name = "Mexican Peso" }, // Объединено с "Mexican New Peso"
            new() { Id = "MNT", Name = "Mongolian Tugrik" },
            new() { Id = "MAD", Name = "Moroccan Dirham" },
            new() { Id = "MZN", Name = "Mozambique Metical" },
            new() { Id = "MMK", Name = "Myanmar Kyat" },
            new() { Id = "NAD", Name = "Namibia Dollar" },
            new() { Id = "NPR", Name = "Nepalese Rupee" },
            new() { Id = "NZD", Name = "New Zealand Dollar" },
            new() { Id = "NIO", Name = "Nicaraguan Cordoba Oro" },
            new() { Id = "NGN", Name = "Nigerian Naira" },
            new() { Id = "ANG", Name = "NL Antillian Guilder" },
            new() { Id = "KPW", Name = "North Korean Won" },
            new() { Id = "NOK", Name = "Norwegian Krona" },
            new() { Id = "OMR", Name = "Omani Rial" },
            new() { Id = "PKR", Name = "Pakistan Rupee" },
            new() { Id = "XPD", Name = "Palladium (oz.)" },
            new() { Id = "PAB", Name = "Panamanian Balboa" },
            new() { Id = "PGK", Name = "Papua New Guinea Kina" },
            new() { Id = "PYG", Name = "Paraguay Guarani" },
            new() { Id = "PEN", Name = "Peruvian Nuevo Sol" },
            new() { Id = "PHP", Name = "Philippine Peso" },
            new() { Id = "XPT", Name = "Platinum (oz.)" },
            new() { Id = "PLN", Name = "Polish Zloty" },
            new() { Id = "GBP", Name = "Pound Sterling" },
            new() { Id = "QAR", Name = "Qatari Rial" },
            new() { Id = "RON", Name = "Romanian Leu" },
            new() { Id = "RUB", Name = "Russian Rouble" }, // Объединено с "Russia Rubles"
            new() { Id = "WST", Name = "Samoan Tala" },
            new() { Id = "STN", Name = "Sao Tome/Principe Dobra" },
            new() { Id = "SAR", Name = "Saudi Arabia Riyal" },
            new() { Id = "SCR", Name = "Seychelles Rupee" },
            new() { Id = "SLL", Name = "Sierra Leone Leone" },
            new() { Id = "XAG", Name = "Silver (oz.)" },
            new() { Id = "SGD", Name = "Singapore Dollar" },
            new() { Id = "SKK", Name = "Slovak Koruna" },
            new() { Id = "SBD", Name = "Solomon Islands Dollar" },
            new() { Id = "SOS", Name = "Somali Shilling" },
            new() { Id = "ZAR", Name = "South African Rand" },
            new() { Id = "LKR", Name = "Sri Lanka Rupee" },
            new() { Id = "SHP", Name = "St. Helena Pound" },
            new() { Id = "SDG", Name = "Sudanese Pound" }, // Объединено с "Sudanese Dinar"
            new() { Id = "SRD", Name = "Surinamese Dollar" },
            new() { Id = "SZL", Name = "Swaziland Lilangeni" },
            new() { Id = "SEK", Name = "Swedish Krona" },
            new() { Id = "CHF", Name = "Swiss Franc" },
            new() { Id = "SYP", Name = "Syrian Pound" },
            new() { Id = "TWD", Name = "Taiwan Dollar" },
            new() { Id = "TZS", Name = "Tanzanian Shilling" },
            new() { Id = "THB", Name = "Thai Baht" },
            new() { Id = "TOP", Name = "Tongan Pa'anga" },
            new() { Id = "TTD", Name = "Trinidad/Tobago Dollar" },
            new() { Id = "TND", Name = "Tunisian Dinar" },
            new() { Id = "TRY", Name = "Turkish Lira" },
            new() { Id = "UGX", Name = "Uganda Shilling" },
            new() { Id = "UAH", Name = "Ukraine Hryvnia" },
            new() { Id = "USD", Name = "United States Dollar" },
            new() { Id = "UYU", Name = "Uruguayan Peso" },
            new() { Id = "AED", Name = "Utd. Arab Emir. Dirham" },
            new() { Id = "VUV", Name = "Vanuatu Vatu" },
            new() { Id = "VEB", Name = "Venezuelan Bolivar" },
            new() { Id = "VND", Name = "Vietnamese Dong" },
            new() { Id = "YER", Name = "Yemeni Riyal" },
            new() { Id = "YUD", Name = "Yugoslavian Dinar" }, // Объединено с "Yugoslav Dinar"
            new() { Id = "ZMW", Name = "Zambian Kwacha" },
            new() { Id = "ZWD", Name = "Zimbabwe Dollar" },
            new() { Id = "XREM", Name = "Remarks" } // Специальный код для "Remarks"
        };

        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id).HasMaxLength(4); // Ограничиваем длину кода
        builder.HasData(currencyList);
    }
}