using DebtusTestTask.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DebtusTestTask.Infrastructure.Configurations;

public class CurrencyConfiguration : IEntityTypeConfiguration<Currency>
{
    public void Configure(EntityTypeBuilder<Currency> builder)
    {
        var currencyList = new Currency[]
        {
            new() { Id = 1, Name = "Cayman Islands Dollar" },
            new() { Id = 2, Name = "Afghanistan Afghani" },
            new() { Id = 3, Name = "Albanian Lek" },
            new() { Id = 4, Name = "Algerian Dinar" },
            new() { Id = 5, Name = "Angolan New Kwanza" },
            new() { Id = 6, Name = "Argentina Pesos" },
            new() { Id = 7, Name = "Argentine Peso" },
            new() { Id = 8, Name = "Aruban Florin" },
            new() { Id = 9, Name = "Australian Dollar" },
            new() { Id = 10, Name = "Bahamian Dollar" },
            new() { Id = 11, Name = "Bahraini Dinar" },
            new() { Id = 12, Name = "Bangladeshi Taka" },
            new() { Id = 13, Name = "Barbados Dollar" },
            new() { Id = 14, Name = "Belize Dollar" },
            new() { Id = 15, Name = "Bermudian Dollar" },
            new() { Id = 16, Name = "Bhutan Ngultrum" },
            new() { Id = 17, Name = "Bolivian Boliviano" },
            new() { Id = 18, Name = "Botswana Pula" },
            new() { Id = 19, Name = "Brazilian Real" },
            new() { Id = 20, Name = "Brunei Dollar" },
            new() { Id = 21, Name = "Bulgarian Lev" },
            new() { Id = 22, Name = "Burundi Franc" },
            new() { Id = 23, Name = "Canadian Dollar" },
            new() { Id = 24, Name = "Cape Verde Escudo" },
            new() { Id = 25, Name = "CFA Franc BCEAO" },
            new() { Id = 26, Name = "CFA Franc BEAC" },
            new() { Id = 27, Name = "CFP Franc" },
            new() { Id = 28, Name = "Chilean Peso" },
            new() { Id = 29, Name = "Chinese Yuan Renminbi" },
            new() { Id = 30, Name = "Colombian Peso" },
            new() { Id = 31, Name = "Comoros Franc" },
            new() { Id = 32, Name = "Costa Rican Colon" },
            new() { Id = 33, Name = "Croatian Kuna" },
            new() { Id = 34, Name = "Cuban Peso" },
            new() { Id = 35, Name = "Cyprus Pound" },
            new() { Id = 36, Name = "Czech Koruna" },
            new() { Id = 37, Name = "Danish Krona" },
            new() { Id = 38, Name = "Djibouti Franc" },
            new() { Id = 39, Name = "Dominican Peso" },
            new() { Id = 40, Name = "Eastern Caribbean Dollars" },
            new() { Id = 41, Name = "Ecuador Sucre" },
            new() { Id = 42, Name = "Egyptian Pound" },
            new() { Id = 43, Name = "El Salvador Colon" },
            new() { Id = 44, Name = "Estonian Krona" },
            new() { Id = 45, Name = "Ethiopian Birr" },
            new() { Id = 46, Name = "Euro" },
            new() { Id = 47, Name = "Falkland Islands Pound" },
            new() { Id = 48, Name = "Fiji Dollar" },
            new() { Id = 49, Name = "Gambian Dalasi" },
            new() { Id = 50, Name = "Ghanaian Cedi" },
            new() { Id = 51, Name = "Gibraltar Pound" },
            new() { Id = 52, Name = "Gold (oz.)" },
            new() { Id = 53, Name = "Guatemalan Quetzal" },
            new() { Id = 54, Name = "Guinea Franc" },
            new() { Id = 55, Name = "Guyanan Dollar" },
            new() { Id = 56, Name = "Haitian Gourde" },
            new() { Id = 57, Name = "Honduran Lempira" },
            new() { Id = 58, Name = "Hong Kong Dollar" },
            new() { Id = 59, Name = "Hungarian Forint" },
            new() { Id = 60, Name = "Iceland Krona" },
            new() { Id = 61, Name = "IMF Special Drawing Right" },
            new() { Id = 62, Name = "Indian Rupee" },
            new() { Id = 63, Name = "Indonesian Rupiah" },
            new() { Id = 64, Name = "Iranian Rial" },
            new() { Id = 65, Name = "Iraqi Dinar" },
            new() { Id = 66, Name = "Israeli New Shekel" },
            new() { Id = 67, Name = "Jamaican Dollar" },
            new() { Id = 68, Name = "Japanese Yen" },
            new() { Id = 69, Name = "Jordanian Dinar" },
            new() { Id = 70, Name = "Kampuchean Riel" },
            new() { Id = 71, Name = "Kazakhstan Tenge" },
            new() { Id = 72, Name = "Kenyan Shilling" },
            new() { Id = 73, Name = "Korean Won" },
            new() { Id = 74, Name = "Kuwaiti Dinar" },
            new() { Id = 75, Name = "Lao Kip" },
            new() { Id = 76, Name = "Latvian Lats" },
            new() { Id = 77, Name = "Lebanese Pound" },
            new() { Id = 78, Name = "Lesotho Loti" },
            new() { Id = 79, Name = "Liberian Dollar" },
            new() { Id = 80, Name = "Libyan Dinar" },
            new() { Id = 81, Name = "Lithuanian Litas" },
            new() { Id = 82, Name = "Macau Pataca" },
            new() { Id = 83, Name = "Malagasy Franc" },
            new() { Id = 84, Name = "Malawi Kwacha" },
            new() { Id = 85, Name = "Malaysian Ringgit" },
            new() { Id = 86, Name = "Maldive Rufiyaa" },
            new() { Id = 87, Name = "Maltese Lira" },
            new() { Id = 88, Name = "Mauritanian Ouguiya" },
            new() { Id = 89, Name = "Mauritius Rupee" },
            new() { Id = 90, Name = "Mexican New Peso" },
            new() { Id = 91, Name = "Mexican Peso" },
            new() { Id = 92, Name = "Mongolian Tugrik" },
            new() { Id = 93, Name = "Moroccan Dirham" },
            new() { Id = 94, Name = "Mozambique Metical" },
            new() { Id = 95, Name = "Myanmar Kyat" },
            new() { Id = 96, Name = "Namibia Dollar" },
            new() { Id = 97, Name = "Nepalese Rupee" },
            new() { Id = 98, Name = "New Zaire" },
            new() { Id = 99, Name = "New Zealand Dollar" },
            new() { Id = 100, Name = "Nicaraguan Cordoba Oro" },
            new() { Id = 101, Name = "Nigerian Naira" },
            new() { Id = 102, Name = "NL Antillian Guilder" },
            new() { Id = 103, Name = "North Korean Won" },
            new() { Id = 104, Name = "Norwegian Krona" },
            new() { Id = 105, Name = "Omani Rial" },
            new() { Id = 106, Name = "Pakistan Rupee" },
            new() { Id = 107, Name = "Palladium (oz.)" },
            new() { Id = 108, Name = "Panamanian Balboa" },
            new() { Id = 109, Name = "Papua New Guinea Kina" },
            new() { Id = 110, Name = "Paraguay Guarani" },
            new() { Id = 111, Name = "Peruvian Nuevo Sol" },
            new() { Id = 112, Name = "Philippine Peso" },
            new() { Id = 113, Name = "Platinum (oz.)" },
            new() { Id = 114, Name = "Polish Zloty" },
            new() { Id = 115, Name = "Pound Sterling" },
            new() { Id = 116, Name = "Qatari Rial" },
            new() { Id = 117, Name = "Romanian Leu" },
            new() { Id = 118, Name = "Russia Rubles" },
            new() { Id = 119, Name = "Russian Rouble" },
            new() { Id = 120, Name = "Samoan Tala" },
            new() { Id = 121, Name = "Sao Tome/Principe Dobra" },
            new() { Id = 122, Name = "Saudi Arabia Riyal" },
            new() { Id = 123, Name = "Seychelles Rupee" },
            new() { Id = 124, Name = "Sierra Leone Leone" },
            new() { Id = 125, Name = "Silver (oz.)" },
            new() { Id = 126, Name = "Singapore Dollar" },
            new() { Id = 127, Name = "Slovak Koruna" },
            new() { Id = 128, Name = "Solomon Islands Dollar" },
            new() { Id = 129, Name = "Somali Shilling" },
            new() { Id = 130, Name = "South African Rand" },
            new() { Id = 131, Name = "Sri Lanka Rupee" },
            new() { Id = 132, Name = "St. Helena Pound" },
            new() { Id = 133, Name = "Sudanese Dinar" },
            new() { Id = 134, Name = "Sudanese Pound" },
            new() { Id = 135, Name = "Surinamese Dollar" },
            new() { Id = 136, Name = "Swaziland Lilangeni" },
            new() { Id = 137, Name = "Swedish Krona" },
            new() { Id = 138, Name = "Swiss Franc" },
            new() { Id = 139, Name = "Syrian Pound" },
            new() { Id = 140, Name = "Taiwan Dollar" },
            new() { Id = 141, Name = "Tanzanian Shilling" },
            new() { Id = 142, Name = "Thai Baht" },
            new() { Id = 143, Name = "Tongan Pa'anga" },
            new() { Id = 144, Name = "Trinidad/Tobago Dollar" },
            new() { Id = 145, Name = "Tunisian Dinar" },
            new() { Id = 146, Name = "Turkish Lira" },
            new() { Id = 147, Name = "Uganda Shilling" },
            new() { Id = 148, Name = "Ukraine Hryvnia" },
            new() { Id = 149, Name = "United States Dollar" },
            new() { Id = 150, Name = "Uruguayan Peso" },
            new() { Id = 151, Name = "Utd. Arab Emir. Dirham" },
            new() { Id = 152, Name = "Vanuatu Vatu" },
            new() { Id = 153, Name = "Venezuelan Bolivar" },
            new() { Id = 154, Name = "Vietnamese Dong" },
            new() { Id = 155, Name = "Yemeni Riyal" },
            new() { Id = 156, Name = "Yugoslav Dinar" },
            new() { Id = 157, Name = "Yugoslavian Dinar" },
            new() { Id = 158, Name = "Zambian Kwacha" },
            new() { Id = 159, Name = "Zimbabwe Dollar" },
            new() { Id = 160, Name = "Remarks" }
    };

        builder.HasData(currencyList);
    }
}
